# Generated by Django 4.1 on 2022-09-03 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('name_work', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('cost_work', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('file_order', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('status_order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ordering.statusorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
